const DebugPage = () => {
  return (

    <div className="flex justify-center">
      <table className="border border-slate-600">
        <tr>
          <th>Env var</th>
          <th>Value</th>
        </tr>
        <tr>
          <td>
            <pre>process.env.NODE_ENV</pre>
          </td>
          <td>
            <pre>{process.env.NODE_ENV}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>process.env.VERCEL</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_ENV</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_ENV}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_URL</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_URL}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_BRANCH_URL</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_BRANCH_URL}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_REGION</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_REGION}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_PROVIDER</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_PROVIDER}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_REPO_SLUG</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_REPO_SLUG}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_REPO_OWNER</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_REPO_OWNER}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_REPO_ID</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_REPO_ID}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_COMMIT_REF</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_COMMIT_REF}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_COMMIT_SHA</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_COMMIT_SHA}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_COMMIT_MESSAGE</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_COMMIT_MESSAGE}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_COMMIT_AUTHOR_LOGIN</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_COMMIT_AUTHOR_LOGIN}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_COMMIT_AUTHOR_NAME</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_COMMIT_AUTHOR_NAME}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_PREVIOUS_SHA</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_PREVIOUS_SHA}</pre>
          </td>
        </tr>
        <tr>
          <td>
            <pre>VERCEL_GIT_PULL_REQUEST_ID</pre>
          </td>
          <td>
            <pre>{process.env.VERCEL_GIT_PULL_REQUEST_ID}</pre>
          </td>
        </tr>
      </table>
    </div>
  );
};

export default DebugPage;
